config/routes.rb
CreateNewContactForm::Application.routes.draw do
  root 'inquiries#index'
  resources :inquiries

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates_presence_of :subject
  validates_presence_of :description
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_email_format_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def index
    @inquiries = Inquiry.all
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)

    if @inquiry.save
      redirect_to inquiries_path, notice: 'Inquiry created successfully'
    else
      render :new
    end
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])

    @inquiry.destroy
    redirect_to inquiries_path, notice: 'Story deleted successfully'
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:first_name,
        :last_name, :email, :subject, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inquiries/_inquiry_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br>

  <%= f.label :subject %>
  <%= f.text_field :subject %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <%= f.submit 'Submit Inquiry' %>
<% end %>

app/views/inquiries/index.html.erb
<h1>All Inquiries</h1>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Subject</th>
  </tr>
  <% @inquiries.each do |inquiry| %>
  <tr>
    <td><%= inquiry.first_name %></td>
    <td><%= inquiry.last_name %></td>
    <td><%= inquiry.email %></td>
    <td><%= link_to inquiry.subject, inquiry_path(inquiry) %></td>
    </tr>
  <% end %>
</table>

app/views/inquiries/new.html.erb
<% if @inquiry.errors.full_messages.any? %>
  <% @inquiry.errors.full_messages.each do |error_message| %>
    <%= error_message %><br>
  <% end %>
<% end %>
<%= render 'inquiry_form' %>

app/views/inquiries/show.html.erb
<%= @inquiry.first_name %>
<%= @inquiry.last_name %>
<%= @inquiry.email %>
<%= @inquiry.subject %>
<%= @inquiry.description %>
<%= link_to 'Destroy Story', @inquiry, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreateNewContactForm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= msg %><br>
  <% end %>

<%= yield %>

<%= link_to 'Contact Us', new_inquiry_path %>

</body>
</html>